# Generated by Django 4.2.30 on 2026-08-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorevent',
            name='device_id',
            field=models.CharField(default='esp32_1', max_length=50),
        ),
    ]
