name: esp32-monitoring

services:
  db:
    image: postgres:16
    container_name: db-postgres
    labels:
      - dockmon.enable=true
      - dockmon.tag=db-tier, critical
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  web:
    build: ./backend
    container_name: django-server
    depends_on:
      - db
    labels:
      - dockmon.enable=true
      - dockmon.tag=web-tier, internal
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"

  bot:
    build: ./bot
    container_name: telegram-bot
    depends_on:
      - web
    labels:
      - dockmon.enable=true
      - dockmon.tag=app-tier, customer-facing
    environment:
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      DJANGO_API_URL: http://web:8000/api/events/

  dockmon:
    image: darthnorse/dockmon:latest
    container_name: dockmon
    restart: unless-stopped
    ports:
      - "8001:443"
    environment:
      - TZ=Europe/Kyiv
      - DOCKMON_FILTER_BY_LABEL=true
    volumes:
      - dockmon_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
  dockmon_data: